# Generated by Django 5.0.1 on 2024-01-28 07:24

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=123)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('image_my', models.ImageField(upload_to='')),
                ('tel', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='UZ')),
                ('address', models.TextField()),
                ('birth', models.DateField()),
                ('project_count', models.IntegerField(blank=True, null=True)),
                ('zip_code', models.IntegerField(blank=True, null=True)),
                ('image_partner', models.ImageField(blank=True, null=True, upload_to='')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
