# Generated by Django 5.0.1 on 2024-01-28 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_aboutme_image_partner_partners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='AboutMe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='blog.aboutme'),
        ),
    ]
