# Generated by Django 5.0.1 on 2024-01-29 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_services'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='blog',
            new_name='author',
        ),
    ]
