# Generated by Django 5.0.1 on 2024-01-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_rename_blog_services_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='lname',
            field=models.CharField(default=1, max_length=123),
            preserve_default=False,
        ),
    ]
