# Generated by Django 5.0.1 on 2024-01-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_results_created_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.IntegerField(choices=[(0, 'Top'), (1, 'low')], default=1)),
                ('name', models.CharField(max_length=123)),
                ('full', models.IntegerField()),
                ('Last_week', models.IntegerField(blank=True, null=True)),
                ('Last_month', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
