# Generated by Django 5.0.1 on 2024-01-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='awards',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
